获取订单详情={
    result=0,
    data={
        wechat_param={
            a=b
        },
        order_detail={
            orderDetailList=[
            {
                goodsPic=http://static.exinetian.com/b2v/goods/image/source/2016329/1459244146320361.jpg,
                frontPrice=2000,
                frontQuantity=1,
                goodsId=1012,
                frontWeight=100,
                goodsName=黑山猪
            }
                             ],
            orderHeader={
                id=1616,
                buyerRemark=1,
                orderCode=OD20160330191692,
                payMode=BA,
                address=虎门镇中心市场1-150号,
                paymentAmount=2000,
                buyerReceiveTime=<null>,
                createTime=2016-03-30 19:48:04,
                consigneeTel1=13625625412,
                marketName=东莞虎门中心农贸市场,
                businessStatus=2,
                marketId=1
            }
        }
    }
}